version: '3.8'

services:
  test-db:
    image: postgres:15
    environment:
      POSTGRES_DB: abhaya_hasta_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # Using different port to avoid conflicts with dev database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5